const { _electron: electron } = require('playwright');
const { spawn } = require('node:child_process');
const { mkdtempSync,mkdirSync,writeFileSync } = require('node:fs');
const { tmpdir } = require('node:os');
const path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),home=mkdtempSync(path.join(tmpdir(),'ken-ui-'));
const python=path.join(root,'.venv',process.platform==='win32'?'Scripts/python.exe':'bin/python');
const server=spawn(python,['tests/desktop_fixture.py',home],{cwd:root});
server.stderr.on('data',c=>process.stderr.write(c));
(async()=>{let app;try{
 const port=await new Promise((resolve,reject)=>{let buf='';const timer=setTimeout(()=>reject(Error('fixture startup timeout')),15000);server.stdout.on('data',c=>{buf+=c;try{const d=JSON.parse(buf.trim());clearTimeout(timer);resolve(d.port);}catch{}});server.on('exit',code=>{clearTimeout(timer);reject(Error('fixture exited '+code));});});
 app=await electron.launch({args:[root],env:{...process.env,KEN_HOME:home,KEN_ENGINE_URL:`http://127.0.0.1:${port}/`}});
 const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.waitForURL(`http://127.0.0.1:${port}/`);
 await app.evaluate(({ipcMain})=>{let connected=false;ipcMain.removeHandler('microphone:permission');ipcMain.handle('microphone:permission',()=>true);ipcMain.removeHandler('account:action');ipcMain.handle('account:action',(_event,action)=>{if(action==='connect')connected=true;return{connected};});});
 await page.reload();await page.getByRole('button',{name:'Connect Claude',exact:true}).click();
 await page.getByRole('button',{name:'Record a voice note',exact:true}).waitFor();
 assert.equal(await page.locator('.side,#chat-context,.header-chrome').count(),0);
 assert.equal(await page.getByRole('button',{name:'Send',exact:true}).count(),0);
 const input=page.getByPlaceholder('Tell Ken what you need…');
 const clear=async()=>{await input.fill('/new');await input.press('Enter');await page.getByText('A fresh thread. What would you like to work on?',{exact:true}).waitFor();};
 mkdirSync(path.join(root,'test-results'),{recursive:true});await page.screenshot({path:path.join(root,'test-results/ken-chat-empty.png')});
 await page.route('**/api/chats/home/messages',async route=>{await new Promise(r=>setTimeout(r,700));await route.continue();});
 await input.fill('Help with a launch');await input.press('Enter');assert.equal(await input.inputValue(),'');await page.getByText('Sending…',{exact:true}).waitFor();await input.fill('Next thought');await page.getByText('did it',{exact:true}).waitFor();assert.equal(await input.inputValue(),'Next thought');await page.unroute('**/api/chats/home/messages');
 await clear();await page.reload();await page.getByText('A fresh thread. What would you like to work on?',{exact:true}).waitFor();
 await input.fill('/');assert.equal(await page.getByRole('option').count(),3);await input.fill('/model');await input.press('Enter');await page.getByText('Choose Claude model',{exact:true}).waitFor();await page.getByRole('button',{name:'sonnet',exact:true}).click();
 await page.evaluate(()=>{const context=new AudioContext(),osc=context.createOscillator(),gain=context.createGain(),dest=context.createMediaStreamDestination();gain.gain.value=.1;osc.connect(gain).connect(dest);osc.start();window.voiceTest={context,osc};navigator.mediaDevices.getUserMedia=async()=>dest.stream;});
 await page.getByRole('button',{name:'Voice',exact:true}).click();await page.locator('[aria-label="Live microphone waveform"]').waitFor();await page.waitForTimeout(400);assert.ok(await page.locator('.recording-input rect').evaluateAll(bars=>bars.some(b=>Number(b.getAttribute('height'))>2)));
 await page.screenshot({path:path.join(root,'test-results/ken-recording.png')});
 await page.route('**/api/voice',async route=>{await new Promise(r=>setTimeout(r,800));await route.continue();});await page.getByRole('button',{name:'Send',exact:true}).click();await input.waitFor();await page.getByRole('button',{name:'Play voice note'}).waitFor();await page.getByRole('button',{name:'Play voice note'}).click();await page.waitForFunction(()=>!!document.querySelector('.voice-note audio')&&!document.querySelector('.voice-note audio').paused);await page.evaluate(()=>{window.sentVoicePlayer=document.querySelector('.voice-note audio');});await input.fill('Still typing');await page.getByText('I run a small agency.',{exact:true}).waitFor();assert.equal(await input.inputValue(),'Still typing');await page.getByText('did it',{exact:true}).waitFor();await page.unroute('**/api/voice');
 assert.equal(await page.locator('.voice-transcript').innerText(),'I run a small agency.');assert.equal(await page.locator('.msg.you .bubble').count(),0);
 assert.equal(await page.evaluate(()=>window.sentVoicePlayer===document.querySelector('.voice-note audio')),true);
 const seek=page.getByRole('slider',{name:'Seek voice note'});await seek.fill('0.1');assert.ok(await page.locator('.voice-note audio').evaluate(audio=>Math.abs(audio.currentTime-.1)<.15));
 await page.screenshot({path:path.join(root,'test-results/ken-voice-message.png')});
 await page.reload();await page.getByRole('button',{name:'Play voice note'}).waitFor();await page.getByRole('button',{name:'Play voice note'}).click();await page.waitForFunction(()=>!document.querySelector('.voice-note audio').paused);await page.getByText('I run a small agency.',{exact:true}).waitFor();
 await clear();await page.locator('input[type=file]').setInputFiles({name:'reference.txt',mimeType:'text/plain',buffer:Buffer.from('Useful reference')});await page.locator('.attached').getByText('reference.txt',{exact:true}).waitFor();await input.fill('Read this');await page.reload();assert.equal(await input.inputValue(),'Read this');await input.press('Enter');await page.getByText('did it',{exact:true}).waitFor();
 writeFileSync(path.join(home,'inbox','launch-notes.md'),'# Launch notes\nUseful first draft.');await page.reload();await page.getByRole('button',{name:/launch-notes.md/}).click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'Close',exact:true}).click();
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(720,600));await page.screenshot({path:path.join(root,'test-results/ken-compact.png')});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);
 console.log('PASS: account flow, compact chat, immediate sending, commands, waveform, voice/transcript persistence, attachments and previews.');
}finally{if(app)await app.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;server.kill();});
